sudo: false

language: c

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
- unset CC
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack $ARGS --no-terminal setup

script:
- wget https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh -O - --quiet | sh -s .
- stack $ARGS --no-terminal test $FLAGS --haddock

cache:
  directories:
  - $HOME/.stack
